<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'AbstractResponseType.php';

/**
 * Returned after taking an action on a dispute with 
 * AddDisputeResponseRequest.Includes the status of the request. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/AddDisputeResponseResponseType.html
 *
 */
class AddDisputeResponseResponseType extends AbstractResponseType
{

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('AddDisputeResponseResponseType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
