<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'AmountType.php';
require_once 'CurrencyCodeType.php';

/**
 * Contains the data for one additional account. An additional account iscreated 
 * when the user has an active account and changes country ofregistry (i.e., 
 * registers with the eBay site for the new country). Anew account is created and 
 * the old account becomes inactive as anadditional account. A user who never 
 * changes country of residency whilehaving an account will never have any 
 * additional accounts. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/AdditionalAccountType.html
 *
 */
class AdditionalAccountType extends EbatNs_ComplexType
{
	/**
	 * @var AmountType
	 */
	protected $Balance;
	/**
	 * @var CurrencyCodeType
	 */
	protected $Currency;
	/**
	 * @var string
	 */
	protected $AccountCode;

	/**
	 * @return AmountType
	 */
	function getBalance()
	{
		return $this->Balance;
	}
	/**
	 * @return void
	 * @param AmountType $value 
	 */
	function setBalance($value)
	{
		$this->Balance = $value;
	}
	/**
	 * @return CurrencyCodeType
	 */
	function getCurrency()
	{
		return $this->Currency;
	}
	/**
	 * @return void
	 * @param CurrencyCodeType $value 
	 */
	function setCurrency($value)
	{
		$this->Currency = $value;
	}
	/**
	 * @return string
	 */
	function getAccountCode()
	{
		return $this->AccountCode;
	}
	/**
	 * @return void
	 * @param string $value 
	 */
	function setAccountCode($value)
	{
		$this->AccountCode = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('AdditionalAccountType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'Balance' =>
				array(
					'required' => false,
					'type' => 'AmountType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Currency' =>
				array(
					'required' => false,
					'type' => 'CurrencyCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'AccountCode' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
