<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'AbstractResponseType.php';

/**
 *  
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/AddToWatchListResponseType.html
 *
 */
class AddToWatchListResponseType extends AbstractResponseType
{
	/**
	 * @var int
	 */
	protected $WatchListCount;
	/**
	 * @var int
	 */
	protected $WatchListMaximum;

	/**
	 * @return int
	 */
	function getWatchListCount()
	{
		return $this->WatchListCount;
	}
	/**
	 * @return void
	 * @param int $value 
	 */
	function setWatchListCount($value)
	{
		$this->WatchListCount = $value;
	}
	/**
	 * @return int
	 */
	function getWatchListMaximum()
	{
		return $this->WatchListMaximum;
	}
	/**
	 * @return void
	 * @param int $value 
	 */
	function setWatchListMaximum($value)
	{
		$this->WatchListMaximum = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('AddToWatchListResponseType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'WatchListCount' =>
				array(
					'required' => false,
					'type' => 'int',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'WatchListMaximum' =>
				array(
					'required' => false,
					'type' => 'int',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
