<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'AuthenticationEntryType.php';

/**
 * Container for a list of AuthenticationEntries. Can contain zero, one, or 
 * multipleAuthenticationEntryType objects. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/AuthenticationEntryArrayType.html
 *
 */
class AuthenticationEntryArrayType extends EbatNs_ComplexType
{
	/**
	 * @var AuthenticationEntryType
	 */
	protected $AuthenticationEntry;

	/**
	 * @return AuthenticationEntryType
	 * @param integer $index 
	 */
	function getAuthenticationEntry($index = null)
	{
		if ($index !== null) {
			return $this->AuthenticationEntry[$index];
		} else {
			return $this->AuthenticationEntry;
		}
	}
	/**
	 * @return void
	 * @param AuthenticationEntryType $value 
	 * @param  $index 
	 */
	function setAuthenticationEntry($value, $index = null)
	{
		if ($index !== null) {
			$this->AuthenticationEntry[$index] = $value;
		} else {
			$this->AuthenticationEntry = $value;
		}
	}
	/**
	 * @return void
	 * @param AuthenticationEntryType $value 
	 */
	function addAuthenticationEntry($value)
	{
		$this->AuthenticationEntry[] = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('AuthenticationEntryArrayType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'AuthenticationEntry' =>
				array(
					'required' => false,
					'type' => 'AuthenticationEntryType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				)
			));

	}
}
?>
