<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'CartItemType.php';

/**
 * A collection of CartItems. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/CartItemArrayType.html
 *
 */
class CartItemArrayType extends EbatNs_ComplexType
{
	/**
	 * @var CartItemType
	 */
	protected $CartItem;

	/**
	 * @return CartItemType
	 * @param integer $index 
	 */
	function getCartItem($index = null)
	{
		if ($index !== null) {
			return $this->CartItem[$index];
		} else {
			return $this->CartItem;
		}
	}
	/**
	 * @return void
	 * @param CartItemType $value 
	 * @param  $index 
	 */
	function setCartItem($value, $index = null)
	{
		if ($index !== null) {
			$this->CartItem[$index] = $value;
		} else {
			$this->CartItem = $value;
		}
	}
	/**
	 * @return void
	 * @param CartItemType $value 
	 */
	function addCartItem($value)
	{
		$this->CartItem[] = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('CartItemArrayType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'CartItem' =>
				array(
					'required' => false,
					'type' => 'CartItemType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				)
			));

	}
}
?>
