<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';

/**
 * Indicates whether automatic declining of best offers is allowed for this 
 * category.Returned only if this category overrides the site default. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/ClassifiedAdAutoDeclineEnabledDefinitionType.html
 *
 */
class ClassifiedAdAutoDeclineEnabledDefinitionType extends EbatNs_ComplexType
{

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('ClassifiedAdAutoDeclineEnabledDefinitionType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
