<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';

/**
 * Indicates which phone option the category supports for contactingthe seller for 
 * Classified Ad format listings.Added for the For Sale By Owner format. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/ClassifiedAdPhoneCountDefinitionType.html
 *
 */
class ClassifiedAdPhoneCountDefinitionType extends EbatNs_ComplexType
{

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('ClassifiedAdPhoneCountDefinitionType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
