<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';

/**
 * Indicates whether Contact Seller is enabled Classified Ads. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/ClassifiedAdPaymentMethodEnabledDefinitionType.html
 *
 */
class ClassifiedAdPaymentMethodEnabledDefinitionType extends EbatNs_ComplexType
{

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('ClassifiedAdPaymentMethodEnabledDefinitionType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
