<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';

/**
 * Indicates whether the telephone can be a contact method for the category. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/ClassifiedAdContactByPhoneEnabledDefinitionType.html
 *
 */
class ClassifiedAdContactByPhoneEnabledDefinitionType extends EbatNs_ComplexType
{

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('ClassifiedAdContactByPhoneEnabledDefinitionType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
