<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'AbstractResponseType.php';

/**
 * Indicates the success or failure of the attempt to leave feedback for the 
 * buyer,change the paid status in My eBay, and/or change the shipped status in My 
 * eBay.<br><br>Applies to Half.com. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/CompleteSaleResponseType.html
 *
 */
class CompleteSaleResponseType extends AbstractResponseType
{

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('CompleteSaleResponseType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
