<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'DigitalDeliveryMethodCodeType.php';

/**
 *  
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/DigitalDeliveryDetailsType.html
 *
 */
class DigitalDeliveryDetailsType extends EbatNs_ComplexType
{
	/**
	 * @var string
	 */
	protected $Requirements;
	/**
	 * @var DigitalDeliveryMethodCodeType
	 */
	protected $Method;
	/**
	 * @var anyURI
	 */
	protected $URL;
	/**
	 * @var string
	 */
	protected $Instructions;

	/**
	 * @return string
	 */
	function getRequirements()
	{
		return $this->Requirements;
	}
	/**
	 * @return void
	 * @param string $value 
	 */
	function setRequirements($value)
	{
		$this->Requirements = $value;
	}
	/**
	 * @return DigitalDeliveryMethodCodeType
	 */
	function getMethod()
	{
		return $this->Method;
	}
	/**
	 * @return void
	 * @param DigitalDeliveryMethodCodeType $value 
	 */
	function setMethod($value)
	{
		$this->Method = $value;
	}
	/**
	 * @return anyURI
	 */
	function getURL()
	{
		return $this->URL;
	}
	/**
	 * @return void
	 * @param anyURI $value 
	 */
	function setURL($value)
	{
		$this->URL = $value;
	}
	/**
	 * @return string
	 */
	function getInstructions()
	{
		return $this->Instructions;
	}
	/**
	 * @return void
	 * @param string $value 
	 */
	function setInstructions($value)
	{
		$this->Instructions = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('DigitalDeliveryDetailsType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'Requirements' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Method' =>
				array(
					'required' => false,
					'type' => 'DigitalDeliveryMethodCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'URL' =>
				array(
					'required' => false,
					'type' => 'anyURI',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Instructions' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
