<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';

/**
 * Indicates whether the category supports the use of email to contact theseller 
 * for Classified Ad format listings.Added for EbayMotors Pro users. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/eBayMotorsProContactByEmailEnabledDefinitionType.html
 *
 */
class eBayMotorsProContactByEmailEnabledDefinitionType extends EbatNs_ComplexType
{

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('eBayMotorsProContactByEmailEnabledDefinitionType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
