<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';

/**
 * Defines the AdFormatEnabled feature. If this field is present, the corresponding 
 * feature applies to the category. The field is returned as an empty element 
 * (e.g., a boolean value is not returned).Added for EbayMotors Pro users. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/eBayMotorsProAdFormatEnabledDefinitionType.html
 *
 */
class eBayMotorsProAdFormatEnabledDefinitionType extends EbatNs_ComplexType
{

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('eBayMotorsProAdFormatEnabledDefinitionType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
