<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'ExpressHistogramDomainDetailsType.php';

/**
 * Details about an Express product type and matching item and catalog product 
 * counts in that product type, if any. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/ExpressHistogramProductType.html
 *
 */
class ExpressHistogramProductType extends EbatNs_ComplexType
{
	/**
	 * @var ExpressHistogramDomainDetailsType
	 */
	protected $DomainDetails;

	/**
	 * @return ExpressHistogramDomainDetailsType
	 */
	function getDomainDetails()
	{
		return $this->DomainDetails;
	}
	/**
	 * @return void
	 * @param ExpressHistogramDomainDetailsType $value 
	 */
	function setDomainDetails($value)
	{
		$this->DomainDetails = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('ExpressHistogramProductType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'DomainDetails' =>
				array(
					'required' => false,
					'type' => 'ExpressHistogramDomainDetailsType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
