<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
require_once 'EbatNs_FacetType.php';

/**
 * For GetSearchResultsExpress, controls the details to retrieve peritem, product, 
 * or histogram. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/ExpressDetailLevelCodeType.html
 *
 * @property string Coarse
 * @property string Fine
 * @property string None
 * @property string CustomCode
 */
class ExpressDetailLevelCodeType extends EbatNs_FacetType
{
	const CodeType_Coarse = 'Coarse';
	const CodeType_Fine = 'Fine';
	const CodeType_None = 'None';
	const CodeType_CustomCode = 'CustomCode';

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('ExpressDetailLevelCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_ExpressDetailLevelCodeType = new ExpressDetailLevelCodeType();

?>
