<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
require_once 'EbatNs_FacetType.php';

/**
 * Sorts the products in ProductArray. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/ExpressProductSortCodeType.html
 *
 * @property string LowestPrice
 * @property string HighestPrice
 * @property string SalesRank
 * @property string CustomCode
 */
class ExpressProductSortCodeType extends EbatNs_FacetType
{
	const CodeType_LowestPrice = 'LowestPrice';
	const CodeType_HighestPrice = 'HighestPrice';
	const CodeType_SalesRank = 'SalesRank';
	const CodeType_CustomCode = 'CustomCode';

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('ExpressProductSortCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_ExpressProductSortCodeType = new ExpressProductSortCodeType();

?>
