<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'ExpressSellingPreferenceCodeType.php';
require_once 'EbatNs_ComplexType.php';

/**
 * Contains a seller's preferences related to listing items on Express. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/ExpressPreferencesType.html
 *
 */
class ExpressPreferencesType extends EbatNs_ComplexType
{
	/**
	 * @var ExpressSellingPreferenceCodeType
	 */
	protected $ExpressSellingPreference;
	/**
	 * @var string
	 */
	protected $DefaultPayPalAccount;

	/**
	 * @return ExpressSellingPreferenceCodeType
	 */
	function getExpressSellingPreference()
	{
		return $this->ExpressSellingPreference;
	}
	/**
	 * @return void
	 * @param ExpressSellingPreferenceCodeType $value 
	 */
	function setExpressSellingPreference($value)
	{
		$this->ExpressSellingPreference = $value;
	}
	/**
	 * @return string
	 */
	function getDefaultPayPalAccount()
	{
		return $this->DefaultPayPalAccount;
	}
	/**
	 * @return void
	 * @param string $value 
	 */
	function setDefaultPayPalAccount($value)
	{
		$this->DefaultPayPalAccount = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('ExpressPreferencesType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'ExpressSellingPreference' =>
				array(
					'required' => false,
					'type' => 'ExpressSellingPreferenceCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'DefaultPayPalAccount' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
