<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';

/**
 * Item details that are only applicable to listings on Express (not the main 
 * eBaysite). 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/ExpressDetailsType.html
 *
 */
class ExpressDetailsType extends EbatNs_ComplexType
{
	/**
	 * @var anyURI
	 */
	protected $ExpressLargeImage;
	/**
	 * @var anyURI
	 */
	protected $ExpressSmallImage;
	/**
	 * @var string
	 */
	protected $Condition;

	/**
	 * @return anyURI
	 */
	function getExpressLargeImage()
	{
		return $this->ExpressLargeImage;
	}
	/**
	 * @return void
	 * @param anyURI $value 
	 */
	function setExpressLargeImage($value)
	{
		$this->ExpressLargeImage = $value;
	}
	/**
	 * @return anyURI
	 */
	function getExpressSmallImage()
	{
		return $this->ExpressSmallImage;
	}
	/**
	 * @return void
	 * @param anyURI $value 
	 */
	function setExpressSmallImage($value)
	{
		$this->ExpressSmallImage = $value;
	}
	/**
	 * @return string
	 */
	function getCondition()
	{
		return $this->Condition;
	}
	/**
	 * @return void
	 * @param string $value 
	 */
	function setCondition($value)
	{
		$this->Condition = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('ExpressDetailsType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'ExpressLargeImage' =>
				array(
					'required' => false,
					'type' => 'anyURI',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ExpressSmallImage' =>
				array(
					'required' => false,
					'type' => 'anyURI',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Condition' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
