<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
require_once 'EbatNs_FacetType.php';

/**
 * Sorts the items in the ItemArray. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/ExpressItemSortCodeType.html
 *
 * @property string LowestTotalCost
 * @property string HighestTotalCost
 * @property string Relevance
 * @property string CustomCode
 */
class ExpressItemSortCodeType extends EbatNs_FacetType
{
	const CodeType_LowestTotalCost = 'LowestTotalCost';
	const CodeType_HighestTotalCost = 'HighestTotalCost';
	const CodeType_Relevance = 'Relevance';
	const CodeType_CustomCode = 'CustomCode';

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('ExpressItemSortCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_ExpressItemSortCodeType = new ExpressItemSortCodeType();

?>
