<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'AmountType.php';

/**
 * Container for external transaction information. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/ExternalTransactionType.html
 *
 */
class ExternalTransactionType extends EbatNs_ComplexType
{
	/**
	 * @var string
	 */
	protected $ExternalTransactionID;
	/**
	 * @var dateTime
	 */
	protected $ExternalTransactionTime;
	/**
	 * @var AmountType
	 */
	protected $FeeOrCreditAmount;
	/**
	 * @var AmountType
	 */
	protected $PaymentOrRefundAmount;

	/**
	 * @return string
	 */
	function getExternalTransactionID()
	{
		return $this->ExternalTransactionID;
	}
	/**
	 * @return void
	 * @param string $value 
	 */
	function setExternalTransactionID($value)
	{
		$this->ExternalTransactionID = $value;
	}
	/**
	 * @return dateTime
	 */
	function getExternalTransactionTime()
	{
		return $this->ExternalTransactionTime;
	}
	/**
	 * @return void
	 * @param dateTime $value 
	 */
	function setExternalTransactionTime($value)
	{
		$this->ExternalTransactionTime = $value;
	}
	/**
	 * @return AmountType
	 */
	function getFeeOrCreditAmount()
	{
		return $this->FeeOrCreditAmount;
	}
	/**
	 * @return void
	 * @param AmountType $value 
	 */
	function setFeeOrCreditAmount($value)
	{
		$this->FeeOrCreditAmount = $value;
	}
	/**
	 * @return AmountType
	 */
	function getPaymentOrRefundAmount()
	{
		return $this->PaymentOrRefundAmount;
	}
	/**
	 * @return void
	 * @param AmountType $value 
	 */
	function setPaymentOrRefundAmount($value)
	{
		$this->PaymentOrRefundAmount = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('ExternalTransactionType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'ExternalTransactionID' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ExternalTransactionTime' =>
				array(
					'required' => false,
					'type' => 'dateTime',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'FeeOrCreditAmount' =>
				array(
					'required' => false,
					'type' => 'AmountType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'PaymentOrRefundAmount' =>
				array(
					'required' => false,
					'type' => 'AmountType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
