<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'FeedbackPeriodType.php';
require_once 'EbatNs_ComplexType.php';

/**
 * Container for a set of feedback statistics. Contains zero one ormultiple 
 * FeedbackPeriod objects. Output only, for the summaryfeedback data returned by 
 * GetFeedback. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/FeedbackPeriodArrayType.html
 *
 */
class FeedbackPeriodArrayType extends EbatNs_ComplexType
{
	/**
	 * @var FeedbackPeriodType
	 */
	protected $FeedbackPeriod;

	/**
	 * @return FeedbackPeriodType
	 * @param integer $index 
	 */
	function getFeedbackPeriod($index = null)
	{
		if ($index !== null) {
			return $this->FeedbackPeriod[$index];
		} else {
			return $this->FeedbackPeriod;
		}
	}
	/**
	 * @return void
	 * @param FeedbackPeriodType $value 
	 * @param  $index 
	 */
	function setFeedbackPeriod($value, $index = null)
	{
		if ($index !== null) {
			$this->FeedbackPeriod[$index] = $value;
		} else {
			$this->FeedbackPeriod = $value;
		}
	}
	/**
	 * @return void
	 * @param FeedbackPeriodType $value 
	 */
	function addFeedbackPeriod($value)
	{
		$this->FeedbackPeriod[] = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('FeedbackPeriodArrayType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'FeedbackPeriod' =>
				array(
					'required' => false,
					'type' => 'FeedbackPeriodType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				)
			));

	}
}
?>
