<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'AmountType.php';
require_once 'FlatRateInsuranceRangeCodeType.php';

/**
 * A pairing of range and insurance cost. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/FlatRateInsuranceRangeCostType.html
 *
 */
class FlatRateInsuranceRangeCostType extends EbatNs_ComplexType
{
	/**
	 * @var FlatRateInsuranceRangeCodeType
	 */
	protected $FlatRateInsuranceRange;
	/**
	 * @var AmountType
	 */
	protected $InsuranceCost;

	/**
	 * @return FlatRateInsuranceRangeCodeType
	 */
	function getFlatRateInsuranceRange()
	{
		return $this->FlatRateInsuranceRange;
	}
	/**
	 * @return void
	 * @param FlatRateInsuranceRangeCodeType $value 
	 */
	function setFlatRateInsuranceRange($value)
	{
		$this->FlatRateInsuranceRange = $value;
	}
	/**
	 * @return AmountType
	 */
	function getInsuranceCost()
	{
		return $this->InsuranceCost;
	}
	/**
	 * @return void
	 * @param AmountType $value 
	 */
	function setInsuranceCost($value)
	{
		$this->InsuranceCost = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('FlatRateInsuranceRangeCostType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'FlatRateInsuranceRange' =>
				array(
					'required' => false,
					'type' => 'FlatRateInsuranceRangeCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'InsuranceCost' =>
				array(
					'required' => false,
					'type' => 'AmountType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
