<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'GetAllBiddersModeCodeType.php';
require_once 'AbstractRequestType.php';
require_once 'ItemIDType.php';

/**
 * Provides three modes for retrieving a list of the users that bidon a listing. 
 * One of the modes is of particular value in support ofthe Second Chance Offer 
 * feature. Includes the list of bidders for therequested item as part of the 
 * general item listing data. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/GetAllBiddersRequestType.html
 *
 */
class GetAllBiddersRequestType extends AbstractRequestType
{
	/**
	 * @var ItemIDType
	 */
	protected $ItemID;
	/**
	 * @var GetAllBiddersModeCodeType
	 */
	protected $CallMode;
	/**
	 * @var boolean
	 */
	protected $IncludeBiddingSummary;

	/**
	 * @return ItemIDType
	 */
	function getItemID()
	{
		return $this->ItemID;
	}
	/**
	 * @return void
	 * @param ItemIDType $value 
	 */
	function setItemID($value)
	{
		$this->ItemID = $value;
	}
	/**
	 * @return GetAllBiddersModeCodeType
	 */
	function getCallMode()
	{
		return $this->CallMode;
	}
	/**
	 * @return void
	 * @param GetAllBiddersModeCodeType $value 
	 */
	function setCallMode($value)
	{
		$this->CallMode = $value;
	}
	/**
	 * @return boolean
	 */
	function getIncludeBiddingSummary()
	{
		return $this->IncludeBiddingSummary;
	}
	/**
	 * @return void
	 * @param boolean $value 
	 */
	function setIncludeBiddingSummary($value)
	{
		$this->IncludeBiddingSummary = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('GetAllBiddersRequestType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'ItemID' =>
				array(
					'required' => false,
					'type' => 'ItemIDType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'CallMode' =>
				array(
					'required' => false,
					'type' => 'GetAllBiddersModeCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'IncludeBiddingSummary' =>
				array(
					'required' => false,
					'type' => 'boolean',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
