<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'ApiAccessRuleType.php';
require_once 'AbstractResponseType.php';

/**
 * Responds to a call to GetApiAccessRules. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/GetApiAccessRulesResponseType.html
 *
 */
class GetApiAccessRulesResponseType extends AbstractResponseType
{
	/**
	 * @var ApiAccessRuleType
	 */
	protected $ApiAccessRule;

	/**
	 * @return ApiAccessRuleType
	 * @param integer $index 
	 */
	function getApiAccessRule($index = null)
	{
		if ($index !== null) {
			return $this->ApiAccessRule[$index];
		} else {
			return $this->ApiAccessRule;
		}
	}
	/**
	 * @return void
	 * @param ApiAccessRuleType $value 
	 * @param  $index 
	 */
	function setApiAccessRule($value, $index = null)
	{
		if ($index !== null) {
			$this->ApiAccessRule[$index] = $value;
		} else {
			$this->ApiAccessRule = $value;
		}
	}
	/**
	 * @return void
	 * @param ApiAccessRuleType $value 
	 */
	function addApiAccessRule($value)
	{
		$this->ApiAccessRule[] = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('GetApiAccessRulesResponseType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'ApiAccessRule' =>
				array(
					'required' => false,
					'type' => 'ApiAccessRuleType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				)
			));

	}
}
?>
