<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'AbstractResponseType.php';

/**
 * Response to GetChallengeToken request. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/GetChallengeTokenResponseType.html
 *
 */
class GetChallengeTokenResponseType extends AbstractResponseType
{
	/**
	 * @var string
	 */
	protected $ChallengeToken;
	/**
	 * @var string
	 */
	protected $ImageChallengeURL;
	/**
	 * @var string
	 */
	protected $AudioChallengeURL;

	/**
	 * @return string
	 */
	function getChallengeToken()
	{
		return $this->ChallengeToken;
	}
	/**
	 * @return void
	 * @param string $value 
	 */
	function setChallengeToken($value)
	{
		$this->ChallengeToken = $value;
	}
	/**
	 * @return string
	 */
	function getImageChallengeURL()
	{
		return $this->ImageChallengeURL;
	}
	/**
	 * @return void
	 * @param string $value 
	 */
	function setImageChallengeURL($value)
	{
		$this->ImageChallengeURL = $value;
	}
	/**
	 * @return string
	 */
	function getAudioChallengeURL()
	{
		return $this->AudioChallengeURL;
	}
	/**
	 * @return void
	 * @param string $value 
	 */
	function setAudioChallengeURL($value)
	{
		$this->AudioChallengeURL = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('GetChallengeTokenResponseType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'ChallengeToken' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ImageChallengeURL' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'AudioChallengeURL' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
