<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'AbstractRequestType.php';

/**
 * Retrieves all the eBay Live Auctions catalogs and upcoming saleschedules that 
 * the user has created. Only returns data if therequestor is an authorized eBay 
 * Live Auctions seller with at leastone catalog. If the seller's auction house has 
 * no upcoming sales,no schedules are returned. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/GetLiveAuctionCatalogDetailsRequestType.html
 *
 */
class GetLiveAuctionCatalogDetailsRequestType extends AbstractRequestType
{

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('GetLiveAuctionCatalogDetailsRequestType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
