<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'AbstractResponseType.php';
require_once 'OrderArrayType.php';

/**
 * Response to GetOrderTransactions request. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/GetOrderTransactionsResponseType.html
 *
 */
class GetOrderTransactionsResponseType extends AbstractResponseType
{
	/**
	 * @var OrderArrayType
	 */
	protected $OrderArray;

	/**
	 * @return OrderArrayType
	 */
	function getOrderArray()
	{
		return $this->OrderArray;
	}
	/**
	 * @return void
	 * @param OrderArrayType $value 
	 */
	function setOrderArray($value)
	{
		$this->OrderArray = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('GetOrderTransactionsResponseType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'OrderArray' =>
				array(
					'required' => false,
					'type' => 'OrderArrayType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
