<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'AbstractRequestType.php';

/**
 * Requests a list of Picture Manager options and allowed values,such as 
 * subscription type and picture display. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/GetPictureManagerOptionsRequestType.html
 *
 */
class GetPictureManagerOptionsRequestType extends AbstractRequestType
{

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('GetPictureManagerOptionsRequestType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
