<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'PictureManagerDetailsType.php';
require_once 'AbstractResponseType.php';

/**
 * Responds with information about content in a Picture Manager albumor the account 
 * settings. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/GetPictureManagerDetailsResponseType.html
 *
 */
class GetPictureManagerDetailsResponseType extends AbstractResponseType
{
	/**
	 * @var PictureManagerDetailsType
	 */
	protected $PictureManagerDetails;

	/**
	 * @return PictureManagerDetailsType
	 */
	function getPictureManagerDetails()
	{
		return $this->PictureManagerDetails;
	}
	/**
	 * @return void
	 * @param PictureManagerDetailsType $value 
	 */
	function setPictureManagerDetails($value)
	{
		$this->PictureManagerDetails = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('GetPictureManagerDetailsResponseType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'PictureManagerDetails' =>
				array(
					'required' => false,
					'type' => 'PictureManagerDetailsType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
