<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'AbstractRequestType.php';

/**
 * Returns a globally unique runame (unique identifier for an authentication 
 * dataentry). <br><br>Unlike most other Trading API calls, this call requires the 
 * eBayUsername and Password values that you created for use by your 
 * applications.(Most Trading API calls, in contrast, require an authentication 
 * token.)These values are not described in thecurrent documentation topic. For 
 * more information about these values,please use the Setup for Authentication link 
 * below. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/GetRuNameRequestType.html
 *
 */
class GetRuNameRequestType extends AbstractRequestType
{
	/**
	 * @var string
	 */
	protected $ClientUseCase;

	/**
	 * @return string
	 */
	function getClientUseCase()
	{
		return $this->ClientUseCase;
	}
	/**
	 * @return void
	 * @param string $value 
	 */
	function setClientUseCase($value)
	{
		$this->ClientUseCase = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('GetRuNameRequestType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'ClientUseCase' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
