<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'AbstractResponseType.php';
require_once 'AuthenticationEntryArrayType.php';

/**
 * Returns all the authentication and authorization preferences and related data 
 * forthe application. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/GetReturnURLResponseType.html
 *
 */
class GetReturnURLResponseType extends AbstractResponseType
{
	/**
	 * @var string
	 */
	protected $ApplicationDisplayName;
	/**
	 * @var AuthenticationEntryArrayType
	 */
	protected $AuthenticationEntryArray;

	/**
	 * @return string
	 */
	function getApplicationDisplayName()
	{
		return $this->ApplicationDisplayName;
	}
	/**
	 * @return void
	 * @param string $value 
	 */
	function setApplicationDisplayName($value)
	{
		$this->ApplicationDisplayName = $value;
	}
	/**
	 * @return AuthenticationEntryArrayType
	 */
	function getAuthenticationEntryArray()
	{
		return $this->AuthenticationEntryArray;
	}
	/**
	 * @return void
	 * @param AuthenticationEntryArrayType $value 
	 */
	function setAuthenticationEntryArray($value)
	{
		$this->AuthenticationEntryArray = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('GetReturnURLResponseType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'ApplicationDisplayName' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'AuthenticationEntryArray' =>
				array(
					'required' => false,
					'type' => 'AuthenticationEntryArrayType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
