<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'AbstractRequestType.php';

/**
 * Retrieves a user's Store preferences. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/GetStorePreferencesRequestType.html
 *
 */
class GetStorePreferencesRequestType extends AbstractRequestType
{

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('GetStorePreferencesRequestType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
