<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'AbstractRequestType.php';

/**
 * Retrieves the custom page or pages for the user's Store. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/GetStoreCustomPageRequestType.html
 *
 */
class GetStoreCustomPageRequestType extends AbstractRequestType
{
	/**
	 * @var long
	 */
	protected $PageID;

	/**
	 * @return long
	 */
	function getPageID()
	{
		return $this->PageID;
	}
	/**
	 * @return void
	 * @param long $value 
	 */
	function setPageID($value)
	{
		$this->PageID = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('GetStoreCustomPageRequestType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'PageID' =>
				array(
					'required' => false,
					'type' => 'long',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
