<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'TokenStatusType.php';
require_once 'AbstractResponseType.php';

/**
 * Returns token status. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/GetTokenStatusResponseType.html
 *
 */
class GetTokenStatusResponseType extends AbstractResponseType
{
	/**
	 * @var TokenStatusType
	 */
	protected $TokenStatus;

	/**
	 * @return TokenStatusType
	 */
	function getTokenStatus()
	{
		return $this->TokenStatus;
	}
	/**
	 * @return void
	 * @param TokenStatusType $value 
	 */
	function setTokenStatus($value)
	{
		$this->TokenStatus = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('GetTokenStatusResponseType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'TokenStatus' =>
				array(
					'required' => false,
					'type' => 'TokenStatusType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
