<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'AbstractResponseType.php';
require_once 'UserType.php';

/**
 * Contains the data retrieved by the call. User data is returned in a User object. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/GetUserResponseType.html
 *
 */
class GetUserResponseType extends AbstractResponseType
{
	/**
	 * @var UserType
	 */
	protected $User;

	/**
	 * @return UserType
	 */
	function getUser()
	{
		return $this->User;
	}
	/**
	 * @return void
	 * @param UserType $value 
	 */
	function setUser($value)
	{
		$this->User = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('GetUserResponseType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'User' =>
				array(
					'required' => false,
					'type' => 'UserType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
