<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';

/**
 * Defines whether Home Page Featured is available on the site. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/HomePageFeaturedEnabledDefinitionType.html
 *
 */
class HomePageFeaturedEnabledDefinitionType extends EbatNs_ComplexType
{

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('HomePageFeaturedEnabledDefinitionType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
