<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';

/**
 * Defines the Item Specific feature. If the field is present, the corresponding 
 * feature applies to the category. The field is returned as an empty element 
 * (e.g., a boolean value is not returned). 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/ItemSpecificsEnabledDefinitionType.html
 *
 */
class ItemSpecificsEnabledDefinitionType extends EbatNs_ComplexType
{

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('ItemSpecificsEnabledDefinitionType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
