<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'LiveAuctionApprovalStatusType.php';

/**
 * Contains the results of the request for each bidder. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/LiveAuctionApprovalStatusArrayType.html
 *
 */
class LiveAuctionApprovalStatusArrayType extends EbatNs_ComplexType
{
	/**
	 * @var LiveAuctionApprovalStatusType
	 */
	protected $LiveAuctionStatus;

	/**
	 * @return LiveAuctionApprovalStatusType
	 * @param integer $index 
	 */
	function getLiveAuctionStatus($index = null)
	{
		if ($index !== null) {
			return $this->LiveAuctionStatus[$index];
		} else {
			return $this->LiveAuctionStatus;
		}
	}
	/**
	 * @return void
	 * @param LiveAuctionApprovalStatusType $value 
	 * @param  $index 
	 */
	function setLiveAuctionStatus($value, $index = null)
	{
		if ($index !== null) {
			$this->LiveAuctionStatus[$index] = $value;
		} else {
			$this->LiveAuctionStatus = $value;
		}
	}
	/**
	 * @return void
	 * @param LiveAuctionApprovalStatusType $value 
	 */
	function addLiveAuctionStatus($value)
	{
		$this->LiveAuctionStatus[] = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('LiveAuctionApprovalStatusArrayType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'LiveAuctionStatus' =>
				array(
					'required' => false,
					'type' => 'LiveAuctionApprovalStatusType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				)
			));

	}
}
?>
