<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'ScheduleType.php';

/**
 * Describes one live auction catalog and its sale schedules.Use this information 
 * to determine an appropriate combination of catalog and schedule IDsin which to 
 * list a lot item when you use AddLiveAuctionItem. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/LiveAuctionCatalogType.html
 *
 */
class LiveAuctionCatalogType extends EbatNs_ComplexType
{
	/**
	 * @var int
	 */
	protected $UserCatalogID;
	/**
	 * @var string
	 */
	protected $CatalogName;
	/**
	 * @var ScheduleType
	 */
	protected $Schedule;

	/**
	 * @return int
	 */
	function getUserCatalogID()
	{
		return $this->UserCatalogID;
	}
	/**
	 * @return void
	 * @param int $value 
	 */
	function setUserCatalogID($value)
	{
		$this->UserCatalogID = $value;
	}
	/**
	 * @return string
	 */
	function getCatalogName()
	{
		return $this->CatalogName;
	}
	/**
	 * @return void
	 * @param string $value 
	 */
	function setCatalogName($value)
	{
		$this->CatalogName = $value;
	}
	/**
	 * @return ScheduleType
	 * @param integer $index 
	 */
	function getSchedule($index = null)
	{
		if ($index !== null) {
			return $this->Schedule[$index];
		} else {
			return $this->Schedule;
		}
	}
	/**
	 * @return void
	 * @param ScheduleType $value 
	 * @param  $index 
	 */
	function setSchedule($value, $index = null)
	{
		if ($index !== null) {
			$this->Schedule[$index] = $value;
		} else {
			$this->Schedule = $value;
		}
	}
	/**
	 * @return void
	 * @param ScheduleType $value 
	 */
	function addSchedule($value)
	{
		$this->Schedule[] = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('LiveAuctionCatalogType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'UserCatalogID' =>
				array(
					'required' => false,
					'type' => 'int',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'CatalogName' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Schedule' =>
				array(
					'required' => false,
					'type' => 'ScheduleType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				)
			));

	}
}
?>
