<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';

/**
 * Indicates whether the category supports using an address when contacting the 
 * seller for Classified Ad format listings. Added for Local Market users. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/LocalMarketContactByAddressEnabledDefinitionType.html
 *
 */
class LocalMarketContactByAddressEnabledDefinitionType extends EbatNs_ComplexType
{

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('LocalMarketContactByAddressEnabledDefinitionType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
