<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';

/**
 * Defines the LocalListingDistancesRegular feature. This feature displays all the 
 * supported local listing distances for items listed by sellers subscribed to 
 * Local Market for Vehicles. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/LocalListingDistancesRegularDefinitionType.html
 *
 */
class LocalListingDistancesRegularDefinitionType extends EbatNs_ComplexType
{

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('LocalListingDistancesRegularDefinitionType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
