<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';

/**
 * Indicates if shipping options are available for Classified Ad format listings in 
 * the category.Added for Local Market users. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/LocalMarketShippingMethodEnabledDefinitionType.html
 *
 */
class LocalMarketShippingMethodEnabledDefinitionType extends EbatNs_ComplexType
{

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('LocalMarketShippingMethodEnabledDefinitionType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
