<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'LookupAttributeType.php';
require_once 'EbatNs_ComplexType.php';

/**
 * Only valid when using AddItem for items in Media categories (Books, DVD 
 * andMovies, Music, and Video Game categories). You can pass 
 * eitherAttributeSetArrayType or LookupAttributeArrayType, but you cannot pass 
 * bothcontainers in the same request. See the eBay Web Services guide for 
 * additionalinformation. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/LookupAttributeArrayType.html
 *
 */
class LookupAttributeArrayType extends EbatNs_ComplexType
{
	/**
	 * @var LookupAttributeType
	 */
	protected $LookupAttribute;

	/**
	 * @return LookupAttributeType
	 * @param integer $index 
	 */
	function getLookupAttribute($index = null)
	{
		if ($index !== null) {
			return $this->LookupAttribute[$index];
		} else {
			return $this->LookupAttribute;
		}
	}
	/**
	 * @return void
	 * @param LookupAttributeType $value 
	 * @param  $index 
	 */
	function setLookupAttribute($value, $index = null)
	{
		if ($index !== null) {
			$this->LookupAttribute[$index] = $value;
		} else {
			$this->LookupAttribute = $value;
		}
	}
	/**
	 * @return void
	 * @param LookupAttributeType $value 
	 */
	function addLookupAttribute($value)
	{
		$this->LookupAttribute[] = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('LookupAttributeArrayType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'LookupAttribute' =>
				array(
					'required' => false,
					'type' => 'LookupAttributeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				)
			));

	}
}
?>
