<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
require_once 'EbatNs_SimpleType.php';

/**
 *  
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/MyMessagesMessageIDType.html
 *
 */
class MyMessagesMessageIDType extends EbatNs_SimpleType
{

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('MyMessagesMessageIDType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_MyMessagesMessageIDType = new MyMessagesMessageIDType();

?>
