<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'MyMessagesMessageIDType.php';

/**
 * Contains a list of up to 10 MessageID values. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/MyMessagesMessageIDArrayType.html
 *
 */
class MyMessagesMessageIDArrayType extends EbatNs_ComplexType
{
	/**
	 * @var MyMessagesMessageIDType
	 */
	protected $MessageID;

	/**
	 * @return MyMessagesMessageIDType
	 * @param integer $index 
	 */
	function getMessageID($index = null)
	{
		if ($index !== null) {
			return $this->MessageID[$index];
		} else {
			return $this->MessageID;
		}
	}
	/**
	 * @return void
	 * @param MyMessagesMessageIDType $value 
	 * @param  $index 
	 */
	function setMessageID($value, $index = null)
	{
		if ($index !== null) {
			$this->MessageID[$index] = $value;
		} else {
			$this->MessageID = $value;
		}
	}
	/**
	 * @return void
	 * @param MyMessagesMessageIDType $value 
	 */
	function addMessageID($value)
	{
		$this->MessageID[] = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('MyMessagesMessageIDArrayType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'MessageID' =>
				array(
					'required' => false,
					'type' => 'MyMessagesMessageIDType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				)
			));

	}
}
?>
