<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'AmountType.php';

/**
 * One of the data filters used when searching for items usingGetSearchResults. 
 * Allows filtering based on the current price of items.Properties allow for 
 * defining a range within prices must fall to bereturned in the result set, a 
 * minimum price for items returned, or amaximum price for items returned. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/PriceRangeFilterType.html
 *
 */
class PriceRangeFilterType extends EbatNs_ComplexType
{
	/**
	 * @var AmountType
	 */
	protected $MaxPrice;
	/**
	 * @var AmountType
	 */
	protected $MinPrice;

	/**
	 * @return AmountType
	 */
	function getMaxPrice()
	{
		return $this->MaxPrice;
	}
	/**
	 * @return void
	 * @param AmountType $value 
	 */
	function setMaxPrice($value)
	{
		$this->MaxPrice = $value;
	}
	/**
	 * @return AmountType
	 */
	function getMinPrice()
	{
		return $this->MinPrice;
	}
	/**
	 * @return void
	 * @param AmountType $value 
	 */
	function setMinPrice($value)
	{
		$this->MinPrice = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('PriceRangeFilterType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'MaxPrice' =>
				array(
					'required' => false,
					'type' => 'AmountType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'MinPrice' =>
				array(
					'required' => false,
					'type' => 'AmountType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
