<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';

/**
 * Contains product information that can be included in a listing.Applicable for 
 * listings that use eBay's Pre-filled Item Information feature.See the Developer's 
 * Guide for details on working with Pre-filled Item Information. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/ProductListingDetailsType.html
 *
 */
class ProductListingDetailsType extends EbatNs_ComplexType
{
	/**
	 * @var string
	 */
	protected $ProductID;
	/**
	 * @var boolean
	 */
	protected $IncludeStockPhotoURL;
	/**
	 * @var boolean
	 */
	protected $IncludePrefilledItemInformation;
	/**
	 * @var boolean
	 */
	protected $UseStockPhotoURLAsGallery;
	/**
	 * @var anyURI
	 */
	protected $StockPhotoURL;
	/**
	 * @var string
	 */
	protected $Copyright;

	/**
	 * @return string
	 */
	function getProductID()
	{
		return $this->ProductID;
	}
	/**
	 * @return void
	 * @param string $value 
	 */
	function setProductID($value)
	{
		$this->ProductID = $value;
	}
	/**
	 * @return boolean
	 */
	function getIncludeStockPhotoURL()
	{
		return $this->IncludeStockPhotoURL;
	}
	/**
	 * @return void
	 * @param boolean $value 
	 */
	function setIncludeStockPhotoURL($value)
	{
		$this->IncludeStockPhotoURL = $value;
	}
	/**
	 * @return boolean
	 */
	function getIncludePrefilledItemInformation()
	{
		return $this->IncludePrefilledItemInformation;
	}
	/**
	 * @return void
	 * @param boolean $value 
	 */
	function setIncludePrefilledItemInformation($value)
	{
		$this->IncludePrefilledItemInformation = $value;
	}
	/**
	 * @return boolean
	 */
	function getUseStockPhotoURLAsGallery()
	{
		return $this->UseStockPhotoURLAsGallery;
	}
	/**
	 * @return void
	 * @param boolean $value 
	 */
	function setUseStockPhotoURLAsGallery($value)
	{
		$this->UseStockPhotoURLAsGallery = $value;
	}
	/**
	 * @return anyURI
	 */
	function getStockPhotoURL()
	{
		return $this->StockPhotoURL;
	}
	/**
	 * @return void
	 * @param anyURI $value 
	 */
	function setStockPhotoURL($value)
	{
		$this->StockPhotoURL = $value;
	}
	/**
	 * @return string
	 * @param integer $index 
	 */
	function getCopyright($index = null)
	{
		if ($index !== null) {
			return $this->Copyright[$index];
		} else {
			return $this->Copyright;
		}
	}
	/**
	 * @return void
	 * @param string $value 
	 * @param  $index 
	 */
	function setCopyright($value, $index = null)
	{
		if ($index !== null) {
			$this->Copyright[$index] = $value;
		} else {
			$this->Copyright = $value;
		}
	}
	/**
	 * @return void
	 * @param string $value 
	 */
	function addCopyright($value)
	{
		$this->Copyright[] = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('ProductListingDetailsType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'ProductID' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'IncludeStockPhotoURL' =>
				array(
					'required' => false,
					'type' => 'boolean',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'IncludePrefilledItemInformation' =>
				array(
					'required' => false,
					'type' => 'boolean',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'UseStockPhotoURLAsGallery' =>
				array(
					'required' => false,
					'type' => 'boolean',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'StockPhotoURL' =>
				array(
					'required' => false,
					'type' => 'anyURI',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Copyright' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => true,
					'cardinality' => '0..*'
				)
			));

	}
}
?>
