<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';

/**
 * Details about a region. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/RegionDetailsType.html
 *
 */
class RegionDetailsType extends EbatNs_ComplexType
{
	/**
	 * @var string
	 */
	protected $RegionID;
	/**
	 * @var string
	 */
	protected $Description;

	/**
	 * @return string
	 */
	function getRegionID()
	{
		return $this->RegionID;
	}
	/**
	 * @return void
	 * @param string $value 
	 */
	function setRegionID($value)
	{
		$this->RegionID = $value;
	}
	/**
	 * @return string
	 */
	function getDescription()
	{
		return $this->Description;
	}
	/**
	 * @return void
	 * @param string $value 
	 */
	function setDescription($value)
	{
		$this->Description = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('RegionDetailsType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'RegionID' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Description' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
