<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'BestOfferArrayType.php';
require_once 'AbstractResponseType.php';

/**
 * Contains a list of BestOffers that were either accepted or declined. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/RespondToBestOfferResponseType.html
 *
 */
class RespondToBestOfferResponseType extends AbstractResponseType
{
	/**
	 * @var BestOfferArrayType
	 */
	protected $RespondToBestOffer;

	/**
	 * @return BestOfferArrayType
	 */
	function getRespondToBestOffer()
	{
		return $this->RespondToBestOffer;
	}
	/**
	 * @return void
	 * @param BestOfferArrayType $value 
	 */
	function setRespondToBestOffer($value)
	{
		$this->RespondToBestOffer = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('RespondToBestOfferResponseType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'RespondToBestOffer' =>
				array(
					'required' => false,
					'type' => 'BestOfferArrayType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
