<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'AbstractResponseType.php';

/**
 * Indicates the success or failure of the attempt to replyto feedback that has 
 * been left for a user, or to post afollow-up comment to a feedback comment a user 
 * has leftfor someone else. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/RespondToFeedbackResponseType.html
 *
 */
class RespondToFeedbackResponseType extends AbstractResponseType
{

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('RespondToFeedbackResponseType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
