<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'AbstractResponseType.php';

/**
 * Response when an application has voluntarily revoked a user token. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/RevokeTokenResponseType.html
 *
 */
class RevokeTokenResponseType extends AbstractResponseType
{

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('RevokeTokenResponseType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
