<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
require_once 'EbatNs_FacetType.php';

/**
 * This is automatic or manual depending on selection. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/SelectionModeCodeType.html
 *
 * @property string Automatic
 * @property string Manual
 * @property string CustomCode
 */
class SelectionModeCodeType extends EbatNs_FacetType
{
	const CodeType_Automatic = 'Automatic';
	const CodeType_Manual = 'Manual';
	const CodeType_CustomCode = 'CustomCode';

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('SelectionModeCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_SelectionModeCodeType = new SelectionModeCodeType();

?>
