<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'CartType.php';
require_once 'AbstractResponseType.php';

/**
 * The response to a call to SetCart. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/SetCartResponseType.html
 *
 */
class SetCartResponseType extends AbstractResponseType
{
	/**
	 * @var CartType
	 */
	protected $Cart;

	/**
	 * @return CartType
	 */
	function getCart()
	{
		return $this->Cart;
	}
	/**
	 * @return void
	 * @param CartType $value 
	 */
	function setCart($value)
	{
		$this->Cart = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('SetCartResponseType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'Cart' =>
				array(
					'required' => false,
					'type' => 'CartType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
