<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'AbstractResponseType.php';

/**
 * (out) Returned after a call to SetNotificationPreferences to indicate that the 
 * call succeeded. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/SetNotificationPreferencesResponseType.html
 *
 */
class SetNotificationPreferencesResponseType extends AbstractResponseType
{

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('SetNotificationPreferencesResponseType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
