<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'AbstractResponseType.php';

/**
 * Confirms whether your application's authentication preferences and other 
 * detailswere configured successfully. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/SetReturnURLResponseType.html
 *
 */
class SetReturnURLResponseType extends AbstractResponseType
{

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('SetReturnURLResponseType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
