<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'StorePreferencesType.php';
require_once 'AbstractRequestType.php';

/**
 * Sets the preferences for a user's eBay Store. These preferences include 
 * variousseller vacation options. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/SetStorePreferencesRequestType.html
 *
 */
class SetStorePreferencesRequestType extends AbstractRequestType
{
	/**
	 * @var StorePreferencesType
	 */
	protected $StorePreferences;

	/**
	 * @return StorePreferencesType
	 */
	function getStorePreferences()
	{
		return $this->StorePreferences;
	}
	/**
	 * @return void
	 * @param StorePreferencesType $value 
	 */
	function setStorePreferences($value)
	{
		$this->StorePreferences = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('SetStorePreferencesRequestType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'StorePreferences' =>
				array(
					'required' => false,
					'type' => 'StorePreferencesType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
