<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'AbstractResponseType.php';

/**
 * The response to a call of SetShippingDiscountProfiles. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/SetShippingDiscountProfilesResponseType.html
 *
 */
class SetShippingDiscountProfilesResponseType extends AbstractResponseType
{

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('SetShippingDiscountProfilesResponseType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
