<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'AbstractResponseType.php';

/**
 * Returned after a call to SetUserPreferences to indicate that the call succeeded. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/SetUserPreferencesResponseType.html
 *
 */
class SetUserPreferencesResponseType extends AbstractResponseType
{

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('SetUserPreferencesResponseType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
