<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'AttributeSetArrayType.php';
require_once 'EbatNs_ComplexType.php';

/**
 * Reserved for future use.. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/SIFFTASRecommendationsType.html
 *
 */
class SIFFTASRecommendationsType extends EbatNs_ComplexType
{
	/**
	 * @var AttributeSetArrayType
	 */
	protected $AttributeSetArray;

	/**
	 * @return AttributeSetArrayType
	 */
	function getAttributeSetArray()
	{
		return $this->AttributeSetArray;
	}
	/**
	 * @return void
	 * @param AttributeSetArrayType $value 
	 */
	function setAttributeSetArray($value)
	{
		$this->AttributeSetArray = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('SIFFTASRecommendationsType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'AttributeSetArray' =>
				array(
					'required' => false,
					'type' => 'AttributeSetArrayType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
