<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
require_once 'EbatNs_SimpleType.php';

/**
 * Type that represents a stock-keeping unit (SKU). The seller can use aSKU to 
 * identify one item or use the same SKU for multiple items.Preferable to 
 * ApplicationData for SKUs and inventory tracking. Differentsellers can use the 
 * same SKUs. This element can be used by sellers totrack complex flows of products 
 * and information. This element preservesa SKU, enabling a seller to obtain it 
 * before and after a transaction iscreated. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/SKUType.html
 *
 */
class SKUType extends EbatNs_SimpleType
{

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('SKUType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_SKUType = new SKUType();

?>
