<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'StoreVacationPreferencesType.php';

/**
 * Store Preferences type. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/StorePreferencesType.html
 *
 */
class StorePreferencesType extends EbatNs_ComplexType
{
	/**
	 * @var StoreVacationPreferencesType
	 */
	protected $VacationPreferences;

	/**
	 * @return StoreVacationPreferencesType
	 */
	function getVacationPreferences()
	{
		return $this->VacationPreferences;
	}
	/**
	 * @return void
	 * @param StoreVacationPreferencesType $value 
	 */
	function setVacationPreferences($value)
	{
		$this->VacationPreferences = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('StorePreferencesType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'VacationPreferences' =>
				array(
					'required' => false,
					'type' => 'StoreVacationPreferencesType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
