<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'SuggestedCategoryType.php';

/**
 * Contains an array of categories that contain listings withspecified keywords in 
 * their titles or descriptions. The arraycan contain up to 10 categories. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/SuggestedCategoryArrayType.html
 *
 */
class SuggestedCategoryArrayType extends EbatNs_ComplexType
{
	/**
	 * @var SuggestedCategoryType
	 */
	protected $SuggestedCategory;

	/**
	 * @return SuggestedCategoryType
	 * @param integer $index 
	 */
	function getSuggestedCategory($index = null)
	{
		if ($index !== null) {
			return $this->SuggestedCategory[$index];
		} else {
			return $this->SuggestedCategory;
		}
	}
	/**
	 * @return void
	 * @param SuggestedCategoryType $value 
	 * @param  $index 
	 */
	function setSuggestedCategory($value, $index = null)
	{
		if ($index !== null) {
			$this->SuggestedCategory[$index] = $value;
		} else {
			$this->SuggestedCategory = $value;
		}
	}
	/**
	 * @return void
	 * @param SuggestedCategoryType $value 
	 */
	function addSuggestedCategory($value)
	{
		$this->SuggestedCategory[] = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('SuggestedCategoryArrayType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'SuggestedCategory' =>
				array(
					'required' => false,
					'type' => 'SuggestedCategoryType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				)
			));

	}
}
?>
