<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
require_once 'EbatNs_FacetType.php';

/**
 * Specifies the site on which the purchase was made. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/TransactionPlatformCodeType.html
 *
 * @property string eBay
 * @property string Express
 * @property string Half
 * @property string Shopping
 * @property string CustomCode
 */
class TransactionPlatformCodeType extends EbatNs_FacetType
{
	const CodeType_eBay = 'eBay';
	const CodeType_Express = 'Express';
	const CodeType_Half = 'Half';
	const CodeType_Shopping = 'Shopping';
	const CodeType_CustomCode = 'CustomCode';

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('TransactionPlatformCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_TransactionPlatformCodeType = new TransactionPlatformCodeType();

?>
