<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'URLTypeCodeType.php';

/**
 * Details about a specific eBay URL. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/URLDetailsType.html
 *
 */
class URLDetailsType extends EbatNs_ComplexType
{
	/**
	 * @var URLTypeCodeType
	 */
	protected $URLType;
	/**
	 * @var anyURI
	 */
	protected $URL;

	/**
	 * @return URLTypeCodeType
	 */
	function getURLType()
	{
		return $this->URLType;
	}
	/**
	 * @return void
	 * @param URLTypeCodeType $value 
	 */
	function setURLType($value)
	{
		$this->URLType = $value;
	}
	/**
	 * @return anyURI
	 */
	function getURL()
	{
		return $this->URL;
	}
	/**
	 * @return void
	 * @param anyURI $value 
	 */
	function setURL($value)
	{
		$this->URL = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('URLDetailsType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'URLType' =>
				array(
					'required' => false,
					'type' => 'URLTypeCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'URL' =>
				array(
					'required' => false,
					'type' => 'anyURI',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
