<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';

/**
 * Container for verified user requirements. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/VerifiedUserRequirementsType.html
 *
 */
class VerifiedUserRequirementsType extends EbatNs_ComplexType
{
	/**
	 * @var boolean
	 */
	protected $VerifiedUser;
	/**
	 * @var int
	 */
	protected $MinimumFeedbackScore;

	/**
	 * @return boolean
	 */
	function getVerifiedUser()
	{
		return $this->VerifiedUser;
	}
	/**
	 * @return void
	 * @param boolean $value 
	 */
	function setVerifiedUser($value)
	{
		$this->VerifiedUser = $value;
	}
	/**
	 * @return int
	 */
	function getMinimumFeedbackScore()
	{
		return $this->MinimumFeedbackScore;
	}
	/**
	 * @return void
	 * @param int $value 
	 */
	function setMinimumFeedbackScore($value)
	{
		$this->MinimumFeedbackScore = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('VerifiedUserRequirementsType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'VerifiedUser' =>
				array(
					'required' => false,
					'type' => 'boolean',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'MinimumFeedbackScore' =>
				array(
					'required' => false,
					'type' => 'int',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
