<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
//
require_once 'VeROReportPacketStatusCodeType.php';
require_once 'AbstractResponseType.php';

/**
 * Contains a packet ID and status for the items reported by the VeRO Program 
 * member. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/VeROReportItemsResponseType.html
 *
 */
class VeROReportItemsResponseType extends AbstractResponseType
{
	/**
	 * @var long
	 */
	protected $VeROReportPacketID;
	/**
	 * @var VeROReportPacketStatusCodeType
	 */
	protected $VeROReportPacketStatus;

	/**
	 * @return long
	 */
	function getVeROReportPacketID()
	{
		return $this->VeROReportPacketID;
	}
	/**
	 * @return void
	 * @param long $value 
	 */
	function setVeROReportPacketID($value)
	{
		$this->VeROReportPacketID = $value;
	}
	/**
	 * @return VeROReportPacketStatusCodeType
	 */
	function getVeROReportPacketStatus()
	{
		return $this->VeROReportPacketStatus;
	}
	/**
	 * @return void
	 * @param VeROReportPacketStatusCodeType $value 
	 */
	function setVeROReportPacketStatus($value)
	{
		$this->VeROReportPacketStatus = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('VeROReportItemsResponseType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'VeROReportPacketID' =>
				array(
					'required' => false,
					'type' => 'long',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'VeROReportPacketStatus' =>
				array(
					'required' => false,
					'type' => 'VeROReportPacketStatusCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
