<?php
// autogenerated file 30.06.2008 14:46
// $Id: $
// $Log: $
//
require_once 'EbatNs_FacetType.php';

/**
 * This type contains ordering criteria for sorting wishlists. The default 
 * orderingis CreationDateAscending. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/WishListSortCodeType.html
 *
 * @property string CreationDateDescending
 * @property string CreationDateAscending
 * @property string PriceAscending
 * @property string PriceDescending
 * @property string CustomCode
 */
class WishListSortCodeType extends EbatNs_FacetType
{
	const CodeType_CreationDateDescending = 'CreationDateDescending';
	const CodeType_CreationDateAscending = 'CreationDateAscending';
	const CodeType_PriceAscending = 'PriceAscending';
	const CodeType_PriceDescending = 'PriceDescending';
	const CodeType_CustomCode = 'CustomCode';

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('WishListSortCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_WishListSortCodeType = new WishListSortCodeType();

?>
